[phases.setup]
nixPkgs = ["python314", "chromium", "libGL", "libGLU"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt",
  "playwright install chromium",
  "playwright install-deps"
]

[start]
cmd = "python src/telegram_bot.py"